- build.gradle
- src/main/generated/inha/dayoook_e/common/QBaseEntity.java
- src/main/generated/inha/dayoook_e/user/domain/QUser.java
- src/main/java/inha/dayoook_e/auth/api/controller/AuthController.java
- src/main/java/inha/dayoook_e/common/BaseEntity.java
- src/main/java/inha/dayoook_e/common/BaseResponse.java
- src/main/java/inha/dayoook_e/common/Constant.java
- src/main/java/inha/dayoook_e/common/code/BaseCode.java
- src/main/java/inha/dayoook_e/common/code/BaseErrorCode.java
- src/main/java/inha/dayoook_e/common/code/ErrorReasonDTO.java
- src/main/java/inha/dayoook_e/common/code/ReasonDTO.java
- src/main/java/inha/dayoook_e/common/code/status/ErrorStatus.java
- src/main/java/inha/dayoook_e/common/code/status/SuccessStatus.java
- src/main/java/inha/dayoook_e/common/config/AppConfig.java
- src/main/java/inha/dayoook_e/common/config/S3Config.java
- src/main/java/inha/dayoook_e/common/config/SecurityConfig.java
- src/main/java/inha/dayoook_e/common/config/SwaggerConfig.java
- src/main/java/inha/dayoook_e/common/config/WebConfig.java
- src/main/java/inha/dayoook_e/common/exceptions/BaseException.java
- src/main/java/inha/dayoook_e/common/exceptions/ExceptionAdvice.java
- src/main/java/inha/dayoook_e/common/exceptions/handler/ExceptionHandler.java
- src/main/java/inha/dayoook_e/user/domain/User.java
- src/main/java/inha/dayoook_e/user/domain/enums/Permission.java
- src/main/java/inha/dayoook_e/user/domain/enums/Role.java
- src/main/java/inha/dayoook_e/user/domain/repository/UserJpaRepository.java
- src/main/java/inha/dayoook_e/utils/ApplicationAuditAware.java
- src/main/java/inha/dayoook_e/utils/jwt/JwtAuthenticationFilter.java
- src/main/java/inha/dayoook_e/utils/jwt/JwtProvider.java
- src/main/java/inha/dayoook_e/utils/jwt/LogoutService.java
- src/main/resources/application-local.yml
> Setting/#1: 프로젝트 기초 세팅

- .github/workflows/deploy-dev.yml
- .gitignore
- appspec-dev.yml
- scripts/start-dev.sh
- scripts/stop-dev.sh
> ci/#10: ci/cd 파이프라인 구축

- src/main/java/inha/dayoook_e/common/Constant.java
- src/main/java/inha/dayoook_e/common/code/status/ErrorStatus.java
- src/main/java/inha/dayoook_e/common/code/status/SuccessStatus.java
- src/main/java/inha/dayoook_e/song/api/service/SongServiceImpl.java
- src/main/java/inha/dayoook_e/song/domain/Song.java
- src/main/java/inha/dayoook_e/song/domain/repository/SongQueryRepository.java
- src/main/java/inha/dayoook_e/storybook/api/controller/StorybookController.java
- src/main/java/inha/dayoook_e/storybook/api/controller/dto/request/CreateStorybookRequest.java
- src/main/java/inha/dayoook_e/storybook/api/controller/dto/request/SearchCond.java
- src/main/java/inha/dayoook_e/storybook/api/controller/dto/response/LastReadPageStorybookResponse.java
- src/main/java/inha/dayoook_e/storybook/api/controller/dto/response/LikedTuteeStorybookProgressResponse.java
- src/main/java/inha/dayoook_e/storybook/api/controller/dto/response/StorybookResponse.java
- src/main/java/inha/dayoook_e/storybook/api/controller/dto/response/StorybookSearchPageResponse.java
- src/main/java/inha/dayoook_e/storybook/api/controller/dto/response/StorybookSearchResponse.java
- src/main/java/inha/dayoook_e/storybook/api/mapper/StorybookMapper.java
- src/main/java/inha/dayoook_e/storybook/api/service/StorybookService.java
- src/main/java/inha/dayoook_e/storybook/api/service/StorybookServiceImpl.java
- src/main/java/inha/dayoook_e/storybook/domain/Storybook.java
- src/main/java/inha/dayoook_e/storybook/domain/StorybookPage.java
- src/main/java/inha/dayoook_e/storybook/domain/TuteeStoryProgress.java
- src/main/java/inha/dayoook_e/storybook/domain/repository/StorybookJpaRepository.java
- src/main/java/inha/dayoook_e/storybook/domain/repository/StorybookPageJpaRepository.java
- src/main/java/inha/dayoook_e/storybook/domain/repository/StorybookQueryRepository.java
- src/main/java/inha/dayoook_e/storybook/domain/repository/TuteeStoryProgressJpaRepository.java
> Feat/#9: 동화 관련 api 개발 완료

- src/main/java/inha/dayoook_e/application/api/controller/ApplicationController.java
- src/main/java/inha/dayoook_e/application/api/service/ApplicationService.java
- src/main/java/inha/dayoook_e/application/api/service/ApplicationServiceImpl.java
- src/main/java/inha/dayoook_e/tutor/api/mapper/TutorScheduleMapper.java
> fix/#15: TutorScheduleMapper 변환 시 default로 변경

- src/main/java/inha/dayoook_e/application/api/service/ApplicationServiceImpl.java
> fix/#18 신청 승인 전에는 스케줄 status 변경하지 않도록 수정

- src/main/java/inha/dayoook_e/tutor/api/controller/dto/request/SearchCond.java
- src/main/java/inha/dayoook_e/tutor/domain/repository/TutorQueryRepository.java
> feat/#24: 검색 조건에 이름 추가 및 언어 및 연령대 리스트 조회 추가

- src/main/java/inha/dayoook_e/tutor/api/controller/dto/response/TutorSearchPageResponse.java
- src/main/java/inha/dayoook_e/tutor/api/controller/dto/response/TutorSearchResponse.java
- src/main/java/inha/dayoook_e/tutor/api/mapper/TutorMapper.java
- src/main/java/inha/dayoook_e/tutor/api/service/TutorServiceImpl.java
- src/main/java/inha/dayoook_e/tutor/domain/repository/TutorQueryRepository.java
> Feat/#27: 튜터 상세조회 기능 수정

- src/main/java/inha/dayoook_e/application/api/controller/ApplicationController.java
- src/main/java/inha/dayoook_e/application/api/controller/dto/request/ApplyRequest.java
- src/main/java/inha/dayoook_e/application/api/controller/dto/request/TimeSlotRequest.java
- src/main/java/inha/dayoook_e/application/api/mapper/ApplicationMapper.java
- src/main/java/inha/dayoook_e/application/api/service/ApplicationService.java
- src/main/java/inha/dayoook_e/application/api/service/ApplicationServiceImpl.java
- src/main/java/inha/dayoook_e/application/domain/Application.java
- src/main/java/inha/dayoook_e/application/domain/ApplicationGroup.java
- src/main/java/inha/dayoook_e/application/domain/repository/ApplicationGroupJpaRepository.java
- src/main/java/inha/dayoook_e/application/domain/repository/ApplicationJpaRepository.java
- src/main/java/inha/dayoook_e/auth/api/service/AuthServiceImpl.java
- src/main/java/inha/dayoook_e/common/code/status/ErrorStatus.java
- src/main/java/inha/dayoook_e/common/code/status/SuccessStatus.java
- src/main/java/inha/dayoook_e/mapping/api/controller/dto/response/SearchDayResponse.java
- src/main/java/inha/dayoook_e/mapping/api/mapper/MappingMapper.java
- src/main/java/inha/dayoook_e/tutor/api/controller/TutorController.java
- src/main/java/inha/dayoook_e/tutor/api/controller/dto/request/ScheduleTimeSlot.java
- src/main/java/inha/dayoook_e/tutor/api/controller/dto/request/TutorScheduleRequest.java
- src/main/java/inha/dayoook_e/tutor/api/controller/dto/response/SearchTutorScheduleResponse.java
- src/main/java/inha/dayoook_e/tutor/api/controller/dto/response/TutorResponse.java
- src/main/java/inha/dayoook_e/tutor/api/controller/dto/response/TutorScheduleData.java
- src/main/java/inha/dayoook_e/tutor/api/mapper/TutorMapper.java
- src/main/java/inha/dayoook_e/tutor/api/service/TutorService.java
- src/main/java/inha/dayoook_e/tutor/api/service/TutorServiceImpl.java
- src/main/java/inha/dayoook_e/tutor/domain/TutorSchedule.java
- src/main/java/inha/dayoook_e/tutor/domain/id/TutorScheduleId.java
- src/main/java/inha/dayoook_e/tutor/domain/repository/TutorScheduleJpaRepository.java
> Feat/#30: 튜터 일정 관련 api 개발

- src/main/java/inha/dayoook_e/tutor/api/controller/dto/response/TutorSearchPageResponse.java
- src/main/java/inha/dayoook_e/tutor/api/controller/dto/response/TutorSearchResponse.java
- src/main/java/inha/dayoook_e/tutor/domain/repository/TutorQueryRepository.java
- src/main/java/inha/dayoook_e/user/api/controller/dto/request/TuteeSignupRequest.java
- src/main/java/inha/dayoook_e/user/api/controller/dto/request/TutorSignupRequest.java
- src/main/java/inha/dayoook_e/user/api/controller/dto/response/TuteeInfoResponse.java
- src/main/java/inha/dayoook_e/user/api/controller/dto/response/TutorInfoResponse.java
- src/main/java/inha/dayoook_e/user/domain/User.java
- src/main/java/inha/dayoook_e/user/domain/enums/KoreanLevel.java
- src/main/resources/application-local.yml
> feat/#32: 한국어 수준 컬럼 추가

- src/main/java/inha/dayoook_e/application/domain/ApplicationGroup.java
- src/main/java/inha/dayoook_e/application/domain/repository/ApplicationGroupJpaRepository.java
- src/main/java/inha/dayoook_e/common/code/status/SuccessStatus.java
- src/main/java/inha/dayoook_e/common/config/WebConfig.java
- src/main/java/inha/dayoook_e/lesson/domain/enums/Status.java
- src/main/java/inha/dayoook_e/lesson/domain/repository/LessonScheduleJpaRepository.java
- src/main/java/inha/dayoook_e/tutee/api/controller/TuteeController.java
- src/main/java/inha/dayoook_e/tutee/api/controller/dto/response/DaySchedule.java
- src/main/java/inha/dayoook_e/tutee/api/controller/dto/response/LessonInfo.java
- src/main/java/inha/dayoook_e/tutee/api/controller/dto/response/TuteeScheduleResponse.java
- src/main/java/inha/dayoook_e/tutee/api/service/TuteeService.java
- src/main/java/inha/dayoook_e/tutee/api/service/TuteeServiceImpl.java
> Feat/#37: cors 설정 변경

- src/main/java/inha/dayoook_e/common/code/status/ErrorStatus.java
- src/main/java/inha/dayoook_e/common/config/RestTemplateConfig.java
- src/main/java/inha/dayoook_e/common/config/WebConfig.java
- src/main/java/inha/dayoook_e/lesson/api/controller/LessonController.java
- src/main/java/inha/dayoook_e/lesson/api/controller/dto/request/MeetingRequest.java
- src/main/java/inha/dayoook_e/lesson/api/controller/dto/response/MeetingResponse.java
- src/main/java/inha/dayoook_e/lesson/api/mapper/LessonMapper.java
- src/main/java/inha/dayoook_e/lesson/api/service/LessonService.java
- src/main/java/inha/dayoook_e/lesson/api/service/LessonServiceImpl.java
- src/main/resources/application-local.yml
> Feat/#39: 구글 미트 api 연동

- src/main/java/inha/dayoook_e/user/domain/UserLanguage.java
> feat: 로그인 시 유저 권한 정보 추가

- src/main/java/inha/dayoook_e/common/config/WebConfig.java
> fix: cors 수정

- src/main/java/inha/dayoook_e/common/config/WebConfig.java
> fix: cors 설정 변경

- src/main/java/inha/dayoook_e/common/config/WebConfig.java
- src/main/java/inha/dayoook_e/tutor/api/controller/dto/response/TutorSearchPageResponse.java
- src/main/java/inha/dayoook_e/tutor/api/controller/dto/response/TutorSearchResponse.java
- src/main/java/inha/dayoook_e/tutor/api/mapper/TutorMapper.java
- src/main/java/inha/dayoook_e/tutor/domain/repository/TutorQueryRepository.java
> feat/#39: 튜터 이미지 추가

- src/main/java/inha/dayoook_e/application/domain/ApplicationGroup.java
> fix: 신청그룹 엔티티 수정

- src/main/java/inha/dayoook_e/application/api/service/ApplicationServiceImpl.java
> feat/#39: 로그 추가

- src/main/java/inha/dayoook_e/application/api/service/ApplicationServiceImpl.java
- src/main/java/inha/dayoook_e/application/domain/repository/ApplicationJpaRepository.java
> feat/#39: 강의 승인 로직 수정

- src/main/java/inha/dayoook_e/lesson/api/controller/LessonController.java
> feat/#39: 헤더 삭제

- src/main/java/inha/dayoook_e/storybook/api/controller/dto/response/StorybookSearchPageResponse.java
> feat/#39: 동화 조건 조회 시 전체 페이지 추가

- src/main/java/inha/dayoook_e/common/code/status/ErrorStatus.java
- src/main/java/inha/dayoook_e/lesson/domain/repository/LessonJpaRepository.java
- src/main/java/inha/dayoook_e/tutor/api/controller/dto/response/SearchTutorApplicationResponse.java
- src/main/java/inha/dayoook_e/tutor/api/mapper/TutorMapper.java
- src/main/java/inha/dayoook_e/tutor/api/service/TutorServiceImpl.java
> feat/#39: 레슨 아이디 추가

- src/main/java/inha/dayoook_e/tutor/api/service/TutorServiceImpl.java
- src/main/java/inha/dayoook_e/user/api/controller/dto/response/UpcomingLessonInfo.java
- src/main/java/inha/dayoook_e/user/api/service/UserServiceImpl.java
> Feat/#39: 미팅 아이디 추가

- src/main/java/inha/dayoook_e/tutor/api/service/TutorServiceImpl.java
> feat/#39: 레슨 로그 추가

- src/main/java/inha/dayoook_e/common/code/status/ErrorStatus.java
- src/main/java/inha/dayoook_e/common/code/status/SuccessStatus.java
- src/main/java/inha/dayoook_e/lesson/api/controller/LessonController.java
- src/main/java/inha/dayoook_e/lesson/api/controller/dto/response/LessonMeetingResponse.java
- src/main/java/inha/dayoook_e/lesson/api/service/LessonService.java
- src/main/java/inha/dayoook_e/lesson/api/service/LessonServiceImpl.java
- src/main/java/inha/dayoook_e/lesson/domain/repository/LessonScheduleJpaRepository.java
- src/main/java/inha/dayoook_e/papago/api/controller/PapagoController.java
- src/main/java/inha/dayoook_e/papago/api/controller/dto/request/PapagoRequest.java
- src/main/java/inha/dayoook_e/papago/api/controller/dto/response/PapagoResponse.java
- src/main/java/inha/dayoook_e/papago/api/service/PapagoService.java
- src/main/java/inha/dayoook_e/papago/api/service/PapagoServiceImpl.java
- src/main/resources/application-local.yml
> Feat/#64: 파파고 api 연결 

- src/main/java/inha/dayoook_e/papago/api/service/PapagoServiceImpl.java
> feat/#66: 파파고 높임말 기능 추가

- src/main/java/inha/dayoook_e/lesson/api/controller/dto/response/LessonSchedulesResponse.java
- src/main/java/inha/dayoook_e/lesson/api/controller/dto/response/TuteeInfoResponse.java
- src/main/java/inha/dayoook_e/lesson/api/service/LessonServiceImpl.java
> feat/#68: 레슨아이디 조회 시 튜티 정보 추가

- build.gradle
> docs/#70: 자바 docs 기반 문서화

- build.gradle
> docs/#70: docs 이름 수정
